import { notFound } from "next/navigation"
import { getInvoiceById } from "@/lib/invoices"

export default async function InvoicePrintPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const invoice = getInvoiceById(id)

  if (!invoice) notFound()

  return (
    <main className="min-h-screen bg-neutral-100 p-8">
      <div className="mx-auto max-w-3xl rounded-2xl bg-white p-10 shadow-sm">
        <div className="mb-8 flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold text-neutral-900">INVOICE</h1>
            <p className="mt-2 text-sm text-neutral-500">
              Blockchain payment invoice
            </p>
          </div>
          <div className="text-right">
            <div className="text-lg font-semibold">{invoice.merchantName}</div>
            <div className="mt-2 text-sm text-neutral-500">
              Invoice ID: {invoice.id}
            </div>
            <div className="text-sm text-neutral-500">
              Date: {new Date(invoice.createdAt).toLocaleString()}
            </div>
          </div>
        </div>

        <div className="mb-8 grid grid-cols-2 gap-8">
          <div>
            <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-neutral-500">
              Bill To
            </h2>
            <p className="text-neutral-900">
              {invoice.customerName || "Walk-in Customer"}
            </p>
          </div>
          <div className="text-right">
            <span
              className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${
                invoice.status === "paid"
                  ? "bg-green-100 text-green-700"
                  : "bg-amber-100 text-amber-700"
              }`}
            >
              {invoice.status.toUpperCase()}
            </span>
          </div>
        </div>

        <div className="overflow-hidden rounded-xl border">
          <table className="w-full border-collapse text-sm">
            <thead className="bg-neutral-50">
              <tr>
                <th className="px-4 py-3 text-left">Item</th>
                <th className="px-4 py-3 text-right">Qty</th>
                <th className="px-4 py-3 text-right">Unit Price</th>
                <th className="px-4 py-3 text-right">Line Total</th>
              </tr>
            </thead>
            <tbody>
              {invoice.items.map((item, index) => (
                <tr key={`${item.name}-${index}`} className="border-t">
                  <td className="px-4 py-3">{item.name}</td>
                  <td className="px-4 py-3 text-right">{item.quantity}</td>
                  <td className="px-4 py-3 text-right">
                    {item.unitPriceTrx} TRX
                  </td>
                  <td className="px-4 py-3 text-right">
                    {(item.quantity * item.unitPriceTrx).toFixed(2)} TRX
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-8 flex items-end justify-between gap-8">
          <div>
            <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-neutral-500">
              Scan to Pay
            </h3>
            <img
              src={invoice.qrDataUrl}
              alt="Invoice payment QR code"
              className="h-44 w-44 rounded-lg border p-2"
            />
            <p className="mt-3 max-w-xs break-all text-xs text-neutral-500">
              {invoice.checkoutUrl}
            </p>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-50 p-5">
            <div className="flex justify-between py-2 text-sm">
              <span className="text-neutral-500">Subtotal</span>
              <span>{invoice.subtotalTrx.toFixed(2)} TRX</span>
            </div>
            <div className="flex justify-between border-t py-3 text-lg font-bold">
              <span>Total</span>
              <span>{invoice.totalTrx.toFixed(2)} TRX</span>
            </div>
          </div>
        </div>

        <div className="mt-10 border-t pt-6 text-xs text-neutral-500">
          This invoice is generated by ReceiptPay. Successful payment can be
          linked to an NFT receipt and on-chain transaction proof.
        </div>
      </div>
    </main>
  )
}